### ISSUE TITLE
Memory Leak Problem

### ISSUE THREAD

**Issue by songyk674** [YvesCoding/vuescroll#79] opened 2018-10-18 03:14 UTC
when i use vuescroll in Vue, there hava a memory leak problem, when I leave the page which use vuescroll,the listener action was not release, the component have no release api to destory ,how can i slove this problem? thanks

**Comment by wangyi7099** [comment] 2018-10-18 03:35
hi, what kind of file did you import? vuescroll.js , vuescroll-native.js or vuescroll-slide.js ?

**Comment by wangyi7099** [comment] 2018-10-18 12:18
Thanks for your feedback. Could you please provide a minimal reproduction?

**Comment by songyk674** [comment] 2018-10-18 12:47
![image](https://user-images.githubusercontent.com/38515410/47155247-e7699e00-d316-11e8-8d88-0144c996b0ff.png)
when i use chrome to detect the memory leak problem, i find many dom was not releasede ,you can see the screenshot.

**Comment by wangyi7099** [comment] 2018-10-18 14:04
Hi, just had a look at screenshot, didn't find memory leak about vuescroll, could you please provide a repro ? Thanks !

**Comment by songyk674** [comment] 2018-10-20 02:04
[vuescroll-example.zip](https://github.com/YvesCoding/vuescroll/files/2497723/vuescroll-example.zip)
the attachement is the example of leak memory,  you can use chrom browser to check the problem, the artical below is the introduction of chrome how to detect the problem.thanks https://forum.vuejs.org/t/vue/28397

**Comment by songyk674** [comment] 2018-10-23 02:52
do you have any new processd?

**Comment by wangyi7099** [comment] 2018-10-23 02:56
Sorry . I'm bussy moving house these days. And I don't have a desk now, I have to buy one on Taobao.com. And desk is not arriving.  I will fix it in the future days. Thanks for your contribution!

**Comment by wangyi7099** [comment] 2018-10-29 11:41
Hi, The reason for this is because `window.resize` is not released  in time. This has been fixed in [`4.9.0-beta.1`](https://github.com/YvesCoding/vuescroll/commit/d02c1fbd22ab51f476e72bdf1b33f5a31485d405). Try latest version can solve this issue.

**Closed by wangyi7099** 2018-10-29 11:41 UTC
